export const AVERAGE_MEASUREMENTS_REQUEST = "AVERAGE_MEASUREMENTS_REQUEST";
export const AVERAGE_MEASUREMENTS_SUCCESS = "AVERAGE_MEASUREMENTS_SUCCESS";
export const AVERAGE_MEASUREMENTS_FAILURE = "AVERAGE_MEASUREMENTS_FAILURE";
export const ALL_MEASUREMENTS_REQUEST = "ALL_MEASUREMENTS_REQUEST";
export const ALL_MEASUREMENTS_SUCCESS = "ALL_MEASUREMENTS_SUCCESS";
export const ALL_MEASUREMENTS_FAILURE = "ALL_MEASUREMENTS_FAILURE";
